### ISSUE TITLE
文章名为中文时候会获取不到文章的json

### ISSUE THREAD

**Issue by xueyou2000** [liujinyang1994/Blog#2]
1. 新建文章 `我的标题`
2. 编译打包, 放到服务器
3. F12进入那一篇文章,发现中文标题被URL编码, `%e6%88%91%e7%9a%84%e6%a0%87%e9%a2%98.json` 获取不到

**Comment by liujinyang1994** [comment]
首先，文件名不可以是中文。
如果不是文件名的问题，那么请将markdown 文件中的
```
---
title: Mocha测试框架
author: Jinyang Liu.
date: "2017-05-09 12:50"
tags:
  - Technology
---
```

这个部分贴出来，我看一下，谢谢😊

**Comment by liujinyang1994** [comment]
如果是文件名的问题，后续我将添加中文文件名转换成拼音文件名的功能，敬请期待！
